import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Header from '@/components/Header'
import Hero from '@/components/Hero'
import About from '@/components/About'
import WorkExperience from '@/components/WorkExperience'
import Skills from '@/components/Skills'
import Projects from '@/components/Projects'
import ContactMe from '@/components/ContactMe'
import { GetStaticProps } from 'next'
import { PageInfo, Experience, Project, Social, Skill } from '@/typings'
import { fetchPageInfo } from '@/utils/fetchPageInfo'
import { fetchExperiences } from '@/utils/fetchExperiences'
import { fetchProjects } from '@/utils/fetchProjects'
import { fetchSkills } from '@/utils/fetchSkills'
import { fetchSocials } from '@/utils/fetchSocials'

type Props = {
    pageInfo: PageInfo;
    experiences: Experience[];
    projects: Project[];
    skills: Skill[];
    socials: Social[];
}

const Home = ({ pageInfo, projects, experiences, skills, socials } : Props) => {
  return (
    <div className="bg-slate-100 text-slate-600 h-screen snap-y snap-mandatory 
    overflow-y-scroll overflow-x-hidden z-0 scrollbar scrollbar-track-slate-600/10 
    scrollbar-thumb-cyan-600/80" >
      <Head>
        <title>{pageInfo.name}&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header socials={socials} />
 
      <section id="hero" className=' snap-start'>
        <Hero pageInfo={pageInfo} />
      </section>
 
      <section id="about" className="snap-center" >
        <About pageInfo={pageInfo} />
      </section>
    
      <section id="experience" className='snap-center'>
        <WorkExperience experiences={experiences} />
      </section>
    
      <section id='skills' className='snap-start'>
        <Skills skills={skills} />
      </section>

      <section id='projects' className='snap-start'>
        <Projects projects={projects} />
      </section>

      <section id="contact" className='snap-start'>
        <ContactMe />
      </section>

      <Link href="#hero">
        <footer className='sticky bottom-5 w-full cursor-pointer'>
          <div className='flex items-center justify-center'>
            <Image 
            width={200}
            height={200}
            className='h-10 w-10 rounded-full filter grayscale hover:grayscale-0'
            src="/images/SuperBass.webp" alt="" />
          </div>
        </footer>
      </Link>
    </div>
  )
}

export default Home

export const getStaticProps: GetStaticProps<Props> = async () => {
    const pageInfo: PageInfo = await fetchPageInfo();
    const experiences: Experience[] = await fetchExperiences();
    const projects: Project[] = await fetchProjects();
    const skills: Skill[] = await fetchSkills();
    const socials: Social[] = await fetchSocials();
  
    return {
      props: {
        pageInfo,
        experiences,
        projects,
        skills,
        socials
      },
      // Next.js will attempt to re-generate the page:
      // -- When a request comes in
      // -- At most one every 10 seconds
      revalidate: 10,
    }
  }